import { Exercise, ExerciseSubstitution } from './types';

export const EXERCISE_CATALOG: Exercise[] = [
  // ══ ГРУДЬ ══
  { id:'bench_bar', name:'Жим штанги лёжа', group:'chest', type:'compound', equipment:'barbell', difficulty:'intermediate', jointStress:'med', fatigueCost:7, targetMuscle:'Большая грудная (центр)', order:1, substitutionGroup:'hor_push', canReplace:['bench_db','dumbbell_press_floor'], cannotReplace:['cable_fly','pec_deck','fly_db'], technique:'Хват чуть шире плеч. Лопатки сведены, грудь «колесом». Опускание на уровень сосков, локти под углом 75°. Не отбивайте штангу!', pauseSeconds:1, peakContraction:false, stretchPhase:true, comments:'Базовое упражнение для груди. Сведение лопаток переносит нагрузку на центр груди, разведение — на широчайшие.' },
  { id:'bench_db', name:'Жим гантелей лёжа', group:'chest', type:'compound', equipment:'dumbbell', difficulty:'intermediate', jointStress:'low', fatigueCost:6, targetMuscle:'Большая грудная (центр)', order:1, substitutionGroup:'hor_push', canReplace:['bench_bar','dumbbell_press_floor'], cannotReplace:['cable_fly','pec_deck'], technique:'Гантели на уровне плеч. В верхней точке сводите гантели — пиковое сокращение груди. Больше ROM чем в жиме штанги.', pauseSeconds:1, peakContraction:true, stretchPhase:true, comments:'Больше амплитуда чем жим штанги. Внизу — растяжение груди, вверху — сведение для пикового сокращения.' },
  { id:'incline_bar', name:'Жим штанги на наклонной (30°)', group:'chest', type:'compound', equipment:'barbell', difficulty:'intermediate', jointStress:'med', fatigueCost:7, targetMuscle:'Большая грудная (верх)', order:1, substitutionGroup:'inc_push', canReplace:['incline_db'], cannotReplace:['cable_fly','pec_deck','fly_db'], technique:'Угол 30°, не 45°! Лопатки сведены. Опускание на верхнюю часть груди. Гриф к подбородку.', pauseSeconds:1, peakContraction:false, stretchPhase:true, comments:'Верхняя часть груди. Угол 30° оптимальнее 45° — при 45° нагрузка переходит на переднюю дельту.' },
  { id:'incline_db', name:'Жим гантелей на наклонной (30°)', group:'chest', type:'compound', equipment:'dumbbell', difficulty:'intermediate', jointStress:'low', fatigueCost:6, targetMuscle:'Большая грудная (верх)', order:1, substitutionGroup:'inc_push', canReplace:['incline_bar'], cannotReplace:['cable_fly','pec_deck'], technique:'Сведение гантель вверху для пикового сокращения. Не разводите локти широко — 75° к телу.', pauseSeconds:1, peakContraction:true, stretchPhase:true, comments:'Верх груди. Пиковое сокращение при сведении — ключ к результату.' },
  { id:'dips_chest', name:'Отжимания на брусьях (грудной стиль)', group:'chest', type:'compound', equipment:'bodyweight', difficulty:'intermediate', jointStress:'high', fatigueCost:8, targetMuscle:'Большая грудная (низ)', order:1, substitutionGroup:'dip_push', canReplace:['dips_tricep','bench_dips'], cannotReplace:['fly_db','cable_fly','pec_deck'], technique:'Наклон корпуса вперёд 30-40°. Локти в стороны. Не запрокидывайте голову. Вниз — растяжение, вверх — мощное сведение.', pauseSeconds:0, peakContraction:true, stretchPhase:true, comments:'Нижняя часть груди. Наклон вперёд = грудь, вертикально = трицепс. Не заменяйте изолирующими!' },
  { id:'decline_bar', name:'Жим штанги на скамье с отрицательным уклоном', group:'chest', type:'compound', equipment:'barbell', difficulty:'intermediate', jointStress:'med', fatigueCost:7, targetMuscle:'Большая грудная (низ)', order:1, substitutionGroup:'decl_push', canReplace:['dips_chest','decline_db'], cannotReplace:['cable_fly','pec_deck'], technique:'Угол -15°. Гриф к нижней части груди. Не выпрямляйте ноги — упор на скамью.', pauseSeconds:1, peakContraction:false, stretchPhase:true, comments:'Нижняя часть груди. Менее эффективно чем брусья, но безопаснее для плеч.' },
  { id:'decline_db', name:'Жим гантелей на скамье с отрицательным уклоном', group:'chest', type:'compound', equipment:'dumbbell', difficulty:'intermediate', jointStress:'low', fatigueCost:6, targetMuscle:'Большая грудная (низ)', order:1, substitutionGroup:'decl_push', canReplace:['decline_bar','dips_chest'], cannotReplace:['fly_db','pec_deck'], technique:'Сведение гантель вверху. Гантели к низу груди.', pauseSeconds:1, peakContraction:true, stretchPhase:true, comments:'Низ груди с лучшей амплитудой чем штанга.' },
  { id:'fly_db', name:'Разводка гантелей лёжа', group:'chest', type:'isolation', equipment:'dumbbell', difficulty:'beginner', jointStress:'low', fatigueCost:4, targetMuscle:'Большая грудная (растяжение)', order:3, substitutionGroup:'chest_iso', canReplace:['cable_fly','pec_deck'], cannotReplace:['bench_bar','bench_db','dips_chest'], technique:'Локти слегка согнуты, фиксированы. Опускание — широкий полукруг до растяжения. Подъём — сведение, как обнимаете дерево.', pauseSeconds:2, peakContraction:true, stretchPhase:true, comments:'Изолирующее! Не заменяет жимы. Фокус на растяжение + пиковое сокращение. Вес次要 — форма важна.' },
  { id:'cable_fly', name:'Сведение в кроссовере (сверху)', group:'chest', type:'isolation', equipment:'cable', difficulty:'beginner', jointStress:'low', fatigueCost:3, targetMuscle:'Большая грудная (центр/низ)', order:3, substitutionGroup:'chest_iso', canReplace:['fly_db','pec_deck'], cannotReplace:['bench_bar','incline_bar','dips_chest'], technique:'Руки вверху — тяните вниз и сводите. В точке сведения — задержка 1-2 секунды (пиковое сокращение).', pauseSeconds:1, peakContraction:true, stretchPhase:false, comments:'Постоянное натяжение в отличие от гантелей. Отлично для пикового сокращения.' },
  { id:'pec_deck', name:'Сведение в тренажёре Butterfly', group:'chest', type:'isolation', equipment:'machine', difficulty:'beginner', jointStress:'low', fatigueCost:3, targetMuscle:'Большая грудная (центр)', order:3, substitutionGroup:'chest_iso', canReplace:['cable_fly','fly_db'], cannotReplace:['bench_bar','dips_chest','incline_bar'], technique:'Сведение до касания. Удержание 1-2 секунды. Не отпускайте вес резко.', pauseSeconds:1, peakContraction:true, stretchPhase:false, comments:'Самый безопасный вариант для пикового сокращения груди. Не заменяет жимы!' },
  { id:'cable_fly_low', name:'Сведение в кроссовере снизу', group:'chest', type:'isolation', equipment:'cable', difficulty:'beginner', jointStress:'low', fatigueCost:3, targetMuscle:'Большая грудная (верх)', order:3, substitutionGroup:'chest_iso_upper', canReplace:['incline_fly_cable'], cannotReplace:['bench_bar','fly_db','cable_fly'], technique:'Руки внизу — тяните вверх и сводите. Акцент на верхнюю часть груди.', pauseSeconds:1, peakContraction:true, stretchPhase:true, comments:'Нагрузка на верх груди. Дополнение к жимам на наклонной, не замена!' },

  // ══ СПИНА ══
  { id:'deadlift', name:'Становая тяга (классика)', group:'back', type:'compound', equipment:'barbell', difficulty:'advanced', jointStress:'high', fatigueCost:10, targetMuscle:'Разгибатели спины, трапеции, задняя цепь', order:1, substitutionGroup:'hip_hinge', canReplace:['rdl','sumo_dl'], cannotReplace:['pulldown','seated_row','straight_pull'], technique:'Нейтральный позвоночник. Таз ниже плеч. Гриф скользит по ногам. Не округляйте поясницу! Двойной перемыв обязательна.', pauseSeconds:2, peakContraction:false, stretchPhase:false, comments:'Самое мощное упражнение. Не заменить тягами блоков! Риск при плохой технике.' },
  { id:'sumo_dl', name:'Становая тяга сумо', group:'back', type:'compound', equipment:'barbell', difficulty:'advanced', jointStress:'med', fatigueCost:9, targetMuscle:'Разгибатели, приводящие, ягодицы', order:1, substitutionGroup:'hip_hinge', canReplace:['deadlift','rdl'], cannotReplace:['pulldown','seated_row'], technique:'Ноги широко, носки наружу. Гриф близко к телу. Короткая амплитуда.', pauseSeconds:2, peakContraction:false, stretchPhase:false, comments:'Альтернатива при проблемах с поясницей. Больше работает внутренняя поверхность бедра.' },
  { id:'pullup', name:'Подтягивания (прямой хват)', group:'back', type:'compound', equipment:'bodyweight', difficulty:'intermediate', jointStress:'med', fatigueCost:7, targetMuscle:'Широчайшие, бицепс', order:1, substitutionGroup:'vert_pull', canReplace:['pulldown','chinup','pullup_neutral'], cannotReplace:['seated_row','face_pull','straight_pull'], technique:'Хват шире плеч на 15-20 см. Тяга локтями вниз, не руками! Сведение лопаток вверху. Без раскачки!', pauseSeconds:1, peakContraction:true, stretchPhase:true, comments:'Сведение лопаток = центр спины/широчайшие. Без сведения = бицепс забирает нагрузку.' },
  { id:'chinup', name:'Подтягивания обратным хватом', group:'back', type:'compound', equipment:'bodyweight', difficulty:'intermediate', jointStress:'med', fatigueCost:7, targetMuscle:'Широчайшие (низ), бицепс', order:1, substitutionGroup:'vert_pull', canReplace:['pullup','pullup_neutral','pulldown_rev'], cannotReplace:['seated_row','face_pull'], technique:'Хват на ширине плеч. Тяга грудью к перекладине. Больше бицепса чем прямой хват.', pauseSeconds:1, peakContraction:true, stretchPhase:true, comments:'Бицепс и низ широчайших. Альтернатива при слабом хвате.' },
  { id:'pullup_neutral', name:'Подтягивания нейтральный хват', group:'back', type:'compound', equipment:'bodyweight', difficulty:'intermediate', jointStress:'low', fatigueCost:7, targetMuscle:'Широчайшие, брахиалис', order:1, substitutionGroup:'vert_pull', canReplace:['pullup','chinup','pulldown'], cannotReplace:['seated_row','face_pull'], technique:'Ладони друг к другу. Тяга локтями. Меньше стресса на плечи.', pauseSeconds:1, peakContraction:true, stretchPhase:true, comments:'Самый безопасный вариант для плеч. Хорошо работает брахиалис.' },
  { id:'pulldown', name:'Тяга верхнего блока (прямой)', group:'back', type:'compound', equipment:'cable', difficulty:'beginner', jointStress:'low', fatigueCost:5, targetMuscle:'Широчайшие', order:1, substitutionGroup:'vert_pull', canReplace:['pullup','pullup_neutral'], cannotReplace:['seated_row','face_pull','straight_pull'], technique:'Хват шире плеч. Тяга к верхней части груди, не за голову! Сведение лопаток. Возврат медленный (2-3 сек).', pauseSeconds:1, peakContraction:true, stretchPhase:true, comments:'Если не можете подтягиваться — начните здесь. Сведение лопаток обязательно!' },
  { id:'pulldown_rev', name:'Тяга верхнего блока обратным хватом', group:'back', type:'compound', equipment:'cable', difficulty:'beginner', jointStress:'low', fatigueCost:5, targetMuscle:'Широчайшие (низ), бицепс', order:1, substitutionGroup:'vert_pull', canReplace:['pulldown','chinup'], cannotReplace:['seated_row','face_pull'], technique:'Хват на ширине плеч обратный. Тяга грудью к рукоятке.', pauseSeconds:1, peakContraction:true, stretchPhase:true, comments:'Больше бицепса. Альтернатива подтягиваниям обратным хватом.' },
  { id:'row_bar', name:'Тяга штанги в наклоне (прямой хват)', group:'back', type:'compound', equipment:'barbell', difficulty:'intermediate', jointStress:'med', fatigueCost:7, targetMuscle:'Широчайшие, ромбовидные, трапеции', order:1, substitutionGroup:'hor_pull', canReplace:['row_db','row_tbar','seated_row'], cannotReplace:['pulldown','straight_pull','cable_fly'], technique:'Наклон 45°. Тяга к низу живота. Локти вдоль тела = широчайшие, локти в стороны = центр спины (ромбовидные). Сведение лопаток!', pauseSeconds:1, peakContraction:true, stretchPhase:true, comments:'Локти вдоль тела → широчайшие. Локти в стороны → ромбовидные/центр. Ключ: сведение лопаток!' },
  { id:'row_tbar', name:'Тяга Т-грифа', group:'back', type:'compound', equipment:'barbell', difficulty:'intermediate', jointStress:'med', fatigueCost:7, targetMuscle:'Центр спины, ромбовидные', order:1, substitutionGroup:'hor_pull', canReplace:['row_bar','row_db','seated_row'], cannotReplace:['pulldown','straight_pull'], technique:'Грудь уперта. Тяга к животу. Локти разводите в стороны для центра спины.', pauseSeconds:1, peakContraction:true, stretchPhase:false, comments:'Отлично для центра спины. Упор груди снижает нагрузку на поясницу.' },
  { id:'row_db', name:'Тяга гантели в наклоне одной рукой', group:'back', type:'compound', equipment:'dumbbell', difficulty:'beginner', jointStress:'low', fatigueCost:5, targetMuscle:'Широчайшие, ромбовидные', order:2, substitutionGroup:'hor_pull', canReplace:['row_bar','seated_row','row_tbar'], cannotReplace:['pulldown','straight_pull','cable_fly'], technique:'Упор рукой и коленом. Тяга к поясу. Вверху — сведение лопатки и разворот — пиковое сокращение.', pauseSeconds:1, peakContraction:true, stretchPhase:true, comments:'Односторонняя работа. Позволяет сильнее растянуть широчайшие внизу и свести лопатку вверху.' },
  { id:'seated_row', name:'Тяга горизонтального блока', group:'back', type:'compound', equipment:'cable', difficulty:'beginner', jointStress:'low', fatigueCost:5, targetMuscle:'Центр спины, ромбовидные', order:2, substitutionGroup:'hor_pull', canReplace:['row_bar','row_db','row_tbar'], cannotReplace:['pulldown','face_pull','straight_pull'], technique:'Грудь вперёд при растяжении, назад при тяге. Сведение лопаток. Не круглите спину!', pauseSeconds:1, peakContraction:true, stretchPhase:true, comments:'Вариативный хват меняет акцент: широкий = широчайшие, узкий = центр.' },
  { id:'face_pull', name:'Тяга к лицу (face pull)', group:'back', type:'isolation', equipment:'cable', difficulty:'beginner', jointStress:'low', fatigueCost:3, targetMuscle:'Задняя дельта, ромбовидные, низ трапеции', order:3, substitutionGroup:'rear_iso', canReplace:['rear_delt_fly','face_pull_sh'], cannotReplace:['row_bar','deadlift','pulldown'], technique:'Трос на уровне глаз. Тяга к лицу, разворот кистей наружу. Сведение лопаток. Медленный возврат (3 сек).', pauseSeconds:1, peakContraction:true, stretchPhase:false, comments:'Незаменимо для здоровья плеч и осанки. Обязательное упражнение!' },
  { id:'straight_pull', name:'Пуловер в блоке прямые руки', group:'back', type:'isolation', equipment:'cable', difficulty:'beginner', jointStress:'low', fatigueCost:4, targetMuscle:'Широчайшие (растяжение)', order:3, substitutionGroup:'lat_iso', canReplace:['pulldown'], cannotReplace:['row_bar','deadlift','face_pull'], technique:'Руки прямые. Тяга вниз до бёдер. Сведение лопаток. Не сгибайте локти!', pauseSeconds:1, peakContraction:true, stretchPhase:true, comments:'Чистая изоляция широчайших. Отличный финал тренировки спины.' },

  // ══ НОГИ ══
  { id:'squat', name:'Приседания со штангой', group:'legs', type:'compound', equipment:'barbell', difficulty:'advanced', jointStress:'high', fatigueCost:10, targetMuscle:'Квадрицепсы, ягодицы, разгибатели', order:1, substitutionGroup:'squat_compound', canReplace:['front_squat','hack_squat','squat_ssb'], cannotReplace:['leg_ext','calf_raise','leg_curl'], technique:'Гриф на трапециях. Ступни на ширине плеч, носки слегка наружу. Глубокий присед (бедра ниже параллели). Колени по линии носков. Грудь вверх!', pauseSeconds:2, peakContraction:false, stretchPhase:true, comments:'Король упражнений. Заменяется ТОЛЬКО другими приседаниями (гакк, фронт, ССБ), НЕ разгибаниями ног!' },
  { id:'front_squat', name:'Фронтальные приседания', group:'legs', type:'compound', equipment:'barbell', difficulty:'advanced', jointStress:'med', fatigueCost:9, targetMuscle:'Квадрицепсы (прямая), верх ягодиц', order:1, substitutionGroup:'squat_compound', canReplace:['squat','hack_squat'], cannotReplace:['leg_ext','calf_raise','leg_curl'], technique:'Гриф на передней дельте. Грудь «колесом». Очень вертикальный корпус. Глубокий присед.', pauseSeconds:2, peakContraction:false, stretchPhase:true, comments:'Больше квадрицепсов чем обычный присед. Меньше нагрузка на поясницу.' },
  { id:'hack_squat', name:'Гакк-приседания', group:'legs', type:'compound', equipment:'machine', difficulty:'intermediate', jointStress:'med', fatigueCost:7, targetMuscle:'Квадрицепсы (латеральная)', order:1, substitutionGroup:'squat_compound', canReplace:['squat','leg_press','front_squat'], cannotReplace:['leg_ext','calf_raise','leg_curl'], technique:'Спина прижата. Ступни ниже на платформе = больше квадрицепсы, выше = больше ягодицы. Полная амплитуда.', pauseSeconds:1, peakContraction:true, stretchPhase:true, comments:'Допустимая замена приседаниям со штангой. Машинный вариант, меньше стресса на поясницу.' },
  { id:'squat_ssb', name:'Приседания ССБ (Safety Squat Bar)', group:'legs', type:'compound', equipment:'barbell', difficulty:'intermediate', jointStress:'med', fatigueCost:8, targetMuscle:'Квадрицепсы, верх спины', order:1, substitutionGroup:'squat_compound', canReplace:['squat','front_squat','hack_squat'], cannotReplace:['leg_ext','calf_raise'], technique:'ССБ на плечах. Хват на ручках. Корпус слегка наклонен. Глубокий присед.', pauseSeconds:2, peakContraction:false, stretchPhase:true, comments:'Отлично при травмах плеч/запястий. Больше работы мышц-стабилизаторов чем в гакке.' },
  { id:'leg_press', name:'Жим ногами (45°)', group:'legs', type:'compound', equipment:'machine', difficulty:'beginner', jointStress:'low', fatigueCost:6, targetMuscle:'Квадрицепсы, ягодицы', order:1, substitutionGroup:'squat_compound', canReplace:['hack_squat','squat'], cannotReplace:['leg_ext','calf_raise','leg_curl'], technique:'Ноги шире = ягодицы, уже = квадрицепсы. Не блокируйте колени! Не отрывайте поясницу!', pauseSeconds:1, peakContraction:true, stretchPhase:true, comments:'Машинная альтернатива приседаниям. Безопаснее для спины. Не заменяет изолирующими!' },
  { id:'rdl', name:'Румынская тяга', group:'legs', type:'compound', equipment:'barbell', difficulty:'intermediate', jointStress:'med', fatigueCost:8, targetMuscle:'Задняя поверхность (бицепс бедра, ягодицы)', order:1, substitutionGroup:'hip_hinge', canReplace:['deadlift','good_morning','rdl_db'], cannotReplace:['leg_curl','leg_ext','calf_raise'], technique:'Ноги чуть согнуты. Таз отводим назад, гриф скользит по ногам. Растяжение в бицепсе бедра — затем мощное сокращение ягодицами.', pauseSeconds:1, peakContraction:true, stretchPhase:true, comments:'Задняя цепь. Растяжение + сокращение — ключ. НЕ кругли поясницу!' },
  { id:'rdl_db', name:'Румынская тяга с гантелями', group:'legs', type:'compound', equipment:'dumbbell', difficulty:'intermediate', jointStress:'low', fatigueCost:7, targetMuscle:'Задняя поверхность', order:1, substitutionGroup:'hip_hinge', canReplace:['rdl','good_morning'], cannotReplace:['leg_curl','leg_ext'], technique:'Гантели вдоль ног. Таз назад. Растяжение бицепса бедра.', pauseSeconds:1, peakContraction:true, stretchPhase:true, comments:'Альтернатива RDL со штангой при проблемах с хватом.' },
  { id:'good_morning', name:'Гудморнинг (наклоны со штангой)', group:'legs', type:'compound', equipment:'barbell', difficulty:'advanced', jointStress:'high', fatigueCost:8, targetMuscle:'Задняя поверхность, разгибатели', order:1, substitutionGroup:'hip_hinge', canReplace:['rdl','deadlift'], cannotReplace:['leg_curl','leg_ext','calf_raise'], technique:'Гриф на трапециях. Наклон с тазом назад. До параллели или чуть ниже. Без округления!', pauseSeconds:1, peakContraction:false, stretchPhase:true, comments:'Задняя цепь и разгибатели. Опасно при проблемах с поясницей. Заменяет RDL.' },
  { id:'lunge', name:'Выпады с гантелями', group:'legs', type:'compound', equipment:'dumbbell', difficulty:'intermediate', jointStress:'med', fatigueCost:7, targetMuscle:'Квадрицепсы, ягодицы', order:2, substitutionGroup:'lunge_var', canReplace:['bulgarian_split','walking_lunge'], cannotReplace:['leg_ext','leg_curl','calf_raise'], technique:'Шаг широкий. Колено задней ноги почти к полу. Корпус вертикально. Не наклоняйтесь!', pauseSeconds:0, peakContraction:true, stretchPhase:true, comments:'Отлично для балансировки ног. Широкий шаг = ягодицы, узкий = квадрицепсы.' },
  { id:'bulgarian_split', name:'Болгарские сплит-приседания', group:'legs', type:'compound', equipment:'dumbbell', difficulty:'intermediate', jointStress:'med', fatigueCost:7, targetMuscle:'Квадрицепсы, ягодицы (односторонние)', order:2, substitutionGroup:'lunge_var', canReplace:['lunge','walking_lunge'], cannotReplace:['leg_ext','leg_curl','calf_raise'], technique:'Задняя нога на скамье. Корпус вертикально. Глубокий присед. Фокус на передней ноге.', pauseSeconds:1, peakContraction:true, stretchPhase:true, comments:'Безальтернативная односторонняя работа. Устраняет дисбаланс ног.' },
  { id:'walking_lunge', name:'Ходьба выпадами', group:'legs', type:'compound', equipment:'dumbbell', difficulty:'intermediate', jointStress:'med', fatigueCost:8, targetMuscle:'Квадрицепсы, ягодицы', order:2, substitutionGroup:'lunge_var', canReplace:['lunge','bulgarian_split'], cannotReplace:['leg_ext','leg_curl'], technique:'Шаг вперёд, глубокий присед, шаг следующей ногой. Без пауз.', pauseSeconds:0, peakContraction:true, stretchPhase:false, comments:'Динамическая версия выпадов. Больше кардио-нагрузки.' },
  { id:'leg_ext', name:'Разгибания ног в тренажёре', group:'legs', type:'isolation', equipment:'machine', difficulty:'beginner', jointStress:'low', fatigueCost:4, targetMuscle:'Квадрицепсы (прямая мышца)', order:3, substitutionGroup:'quad_iso', canReplace:['sissy_squat'], cannotReplace:['squat','hack_squat','leg_press','front_squat'], technique:'Полное разгибание. Удержание 1-2 сек вверху (пиковое сокращение). Медленный возврат (3 сек).', pauseSeconds:2, peakContraction:true, stretchPhase:false, comments:'ТОЛЬКО изоляция! НЕ заменяет приседания. Дополнение, не основа.' },
  { id:'leg_curl', name:'Сгибания ног в тренажёре лёжа', group:'legs', type:'isolation', equipment:'machine', difficulty:'beginner', jointStress:'low', fatigueCost:4, targetMuscle:'Бицепс бедра', order:3, substitutionGroup:'ham_iso', canReplace:['leg_curl_seated','leg_curl_standing'], cannotReplace:['rdl','deadlift','good_morning'], technique:'Полное сгибание. Удержание 1-2 сек. Не отрывайте таз! Медленный возврат.', pauseSeconds:1, peakContraction:true, stretchPhase:false, comments:'Изоляция бицепса бедра. НЕ заменяет RDL. RDL + leg curl = полная тренировка задней поверхности.' },
  { id:'leg_curl_seated', name:'Сгибания ног сидя', group:'legs', type:'isolation', equipment:'machine', difficulty:'beginner', jointStress:'low', fatigueCost:4, targetMuscle:'Бицепс бедра', order:3, substitutionGroup:'ham_iso', canReplace:['leg_curl','leg_curl_standing'], cannotReplace:['rdl','deadlift'], technique:'Сидя. Полное сгибание. Удержание наверху.', pauseSeconds:1, peakContraction:true, stretchPhase:false, comments:'Вариант для тех, у кого дискомфорт при лёжем сгибании.' },
  { id:'leg_curl_standing', name:'Сгибания ног стоя (по одной)', group:'legs', type:'isolation', equipment:'machine', difficulty:'beginner', jointStress:'low', fatigueCost:3, targetMuscle:'Бицепс бедра', order:3, substitutionGroup:'ham_iso', canReplace:['leg_curl','leg_curl_seated'], cannotReplace:['rdl','deadlift'], technique:'По одной ноге. Полное сгибание, пиковое сокращение.', pauseSeconds:1, peakContraction:true, stretchPhase:false, comments:'Односторонняя работа. Устраняет дисбаланс.' },
  { id:'calf_raise', name:'Подъёмы на носки стоя', group:'legs', type:'isolation', equipment:'machine', difficulty:'beginner', jointStress:'low', fatigueCost:3, targetMuscle:'Икроножные (камбаловидная + икроножная)', order:4, substitutionGroup:'calf_iso', canReplace:['calf_raise_seated','calf_press'], cannotReplace:['squat','leg_press','leg_ext'], technique:'Полная амплитуда — ниже уровня платформы. Удержание 2 сек наверху. Медленный возврат (3 сек).', pauseSeconds:2, peakContraction:true, stretchPhase:true, comments:'Полная амплитуда критична! Большинство делают слишком коротко.' },
  { id:'calf_raise_seated', name:'Подъёмы на носки сидя', group:'legs', type:'isolation', equipment:'machine', difficulty:'beginner', jointStress:'low', fatigueCost:3, targetMuscle:'Камбаловидная', order:4, substitutionGroup:'calf_iso', canReplace:['calf_raise','calf_press'], cannotReplace:['squat','leg_press'], technique:'Полная амплитуда. Удержание 2 сек наверху.', pauseSeconds:2, peakContraction:true, stretchPhase:true, comments:'Акцент на камбаловидную (под икроножной).' },
  { id:'hip_thrust', name:'Ягодичный мост со штангой', group:'legs', type:'compound', equipment:'barbell', difficulty:'intermediate', jointStress:'low', fatigueCost:6, targetMuscle:'Ягодицы', order:2, substitutionGroup:'glute_compound', canReplace:['glute_bridge','cable_kickback'], cannotReplace:['leg_ext','leg_curl','calf_raise'], technique:'Гриф на складке таза. Таз вверх — мощное сокращение ягодиц. Удержание 2 сек наверху. Не гиперэкстензия!', pauseSeconds:2, peakContraction:true, stretchPhase:true, comments:'Лучшее упражнение для ягодиц. Пиковое сокращение + растяжение = рост.' },
  { id:'glute_bridge', name:'Ягодичный мост на полу', group:'legs', type:'compound', equipment:'bodyweight', difficulty:'beginner', jointStress:'low', fatigueCost:4, targetMuscle:'Ягодицы', order:2, substitutionGroup:'glute_compound', canReplace:['hip_thrust'], cannotReplace:['leg_ext','leg_curl'], technique:'Таз вверх, сокращение ягодиц. Удержание 2 сек.', pauseSeconds:2, peakContraction:true, stretchPhase:false, comments:'Начальный вариант для новичков перед hip thrust.' },

  // ══ ПЛЕЧИ ══
  { id:'ohp', name:'Армейский жим стоя', group:'shoulders', type:'compound', equipment:'barbell', difficulty:'intermediate', jointStress:'med', fatigueCost:7, targetMuscle:'Передняя + средняя дельта, трицепс', order:1, substitutionGroup:'ohp_var', canReplace:['db_press','ohp_seated','push_press'], cannotReplace:['lateral_raise','rear_delt_fly','face_pull_sh'], technique:'Хват чуть шире плеч. Гриф к ключице. Жим вверх за голову. Не выгибайте поясницу! Таз напряжён.', pauseSeconds:1, peakContraction:true, stretchPhase:false, comments:'Базовое упражнение для дельт. Стоя = больше стабилизаторов, сидя = больше изоляция.' },
  { id:'db_press', name:'Жим гантелей сидя', group:'shoulders', type:'compound', equipment:'dumbbell', difficulty:'intermediate', jointStress:'med', fatigueCost:6, targetMuscle:'Передняя + средняя дельта', order:1, substitutionGroup:'ohp_var', canReplace:['ohp','ohp_seated','push_press'], cannotReplace:['lateral_raise','rear_delt_fly'], technique:'Внизу — гантели на уровне ушей. Вверху — сведение. Не отбивайте!', pauseSeconds:1, peakContraction:true, stretchPhase:false, comments:'Больше амплитуда чем OHP. Сведение гантелей = пиковое сокращение.' },
  { id:'ohp_seated', name:'Армейский жим сидя', group:'shoulders', type:'compound', equipment:'barbell', difficulty:'intermediate', jointStress:'low', fatigueCost:6, targetMuscle:'Передняя дельта', order:1, substitutionGroup:'ohp_var', canReplace:['ohp','db_press'], cannotReplace:['lateral_raise','rear_delt_fly'], technique:'Сидя с упором. Меньше стабилизации = больше изоляция.', pauseSeconds:1, peakContraction:true, stretchPhase:false, comments:'Сидя убирает ноги из движения. Чище изоляция дельт.' },
  { id:'push_press', name:'Жимовой швунг', group:'shoulders', type:'compound', equipment:'barbell', difficulty:'advanced', jointStress:'high', fatigueCost:8, targetMuscle:'Дельты (всё), трицепс, ноги', order:1, substitutionGroup:'ohp_var', canReplace:['ohp','db_press'], cannotReplace:['lateral_raise','rear_delt_fly'], technique:'Толчок ногами + жим. Больше вес. Для силового цикла.', pauseSeconds:0, peakContraction:false, stretchPhase:false, comments:'Силовой вариант OHP. Ноги помогают. Только для продвинутых!' },
  { id:'lateral_raise', name:'Махи гантелями в стороны', group:'shoulders', type:'isolation', equipment:'dumbbell', difficulty:'beginner', jointStress:'low', fatigueCost:4, targetMuscle:'Средняя дельта', order:2, substitutionGroup:'lat_delt_iso', canReplace:['cable_lateral','lateral_machine'], cannotReplace:['ohp','db_press','rear_delt_fly'], technique:'Чуть наклон вперёд. Мах до уровня плеч. Локти чуть согнуты. Не выше плеч — это трапеция! Разворот мизинцем вверх.', pauseSeconds:1, peakContraction:true, stretchPhase:false, comments:'Не заменяет жимы! Средняя дельта изолированно. Пиковое сокращение наверху = ключ к результату.' },
  { id:'cable_lateral', name:'Отведение в кроссовере (снизу)', group:'shoulders', type:'isolation', equipment:'cable', difficulty:'beginner', jointStress:'low', fatigueCost:3, targetMuscle:'Средняя дельта', order:2, substitutionGroup:'lat_delt_iso', canReplace:['lateral_raise','lateral_machine'], cannotReplace:['ohp','db_press'], technique:'Одной рукой. Трос снизу. Отведение до уровня плеч. Постоянное натяжение!', pauseSeconds:1, peakContraction:true, stretchPhase:false, comments:'Постоянное натяжение = больше времени под нагрузкой чем гантели.' },
  { id:'rear_delt_fly', name:'Махи в наклоне на заднюю дельту', group:'shoulders', type:'isolation', equipment:'dumbbell', difficulty:'beginner', jointStress:'low', fatigueCost:3, targetMuscle:'Задняя дельта', order:2, substitutionGroup:'rear_delt_iso', canReplace:['face_pull','face_pull_sh','rear_delt_machine'], cannotReplace:['ohp','db_press','lateral_raise'], technique:'Наклон 60-70°. Махи в стороны, локти вверх. Мизинец ведёт движение. Не круглите спину!', pauseSeconds:1, peakContraction:true, stretchPhase:false, comments:'Задняя дельта — самая отстающая. Локти вверх, не назад!' },
  { id:'rear_delt_machine', name:'Обратные сведения в тренажёре', group:'shoulders', type:'isolation', equipment:'machine', difficulty:'beginner', jointStress:'low', fatigueCost:3, targetMuscle:'Задняя дельта, ромбовидные', order:2, substitutionGroup:'rear_delt_iso', canReplace:['rear_delt_fly','face_pull'], cannotReplace:['ohp','lateral_raise'], technique:'Грудь на подушке. Разведение назад. Сведение лопаток.', pauseSeconds:1, peakContraction:true, stretchPhase:false, comments:'Безопаснее для поясницы чем махи в наклоне.' },
  { id:'upright_row', name:'Тяга штанги к подбородку', group:'shoulders', type:'compound', equipment:'barbell', difficulty:'intermediate', jointStress:'high', fatigueCost:6, targetMuscle:'Средняя дельта, трапеция', order:3, substitutionGroup:'upright_var', canReplace:['cable_upright'], cannotReplace:['ohp','lateral_raise','rear_delt_fly'], technique:'Узкий хват. Тяга до уровня сосков, НЕ до подбородка! Не выше — иначе импинджмент.', pauseSeconds:0, peakContraction:true, stretchPhase:false, comments:'Осторожно с плечами! Не тяните выше уровня сосков — риск импинджмент-синдрома.' },
  { id:'face_pull_sh', name:'Тяга к лицу (задняя дельта)', group:'shoulders', type:'isolation', equipment:'cable', difficulty:'beginner', jointStress:'low', fatigueCost:3, targetMuscle:'Задняя дельта, ромбовидные', order:3, substitutionGroup:'rear_delt_iso', canReplace:['face_pull','rear_delt_fly'], cannotReplace:['ohp','lateral_raise','db_press'], technique:'См. face_pull (спина). Акцент на заднюю дельту через разворот кистей.', pauseSeconds:1, peakContraction:true, stretchPhase:false, comments:'Лучшее упражнение для задней дельты и здоровья плеч.' },

  // ══ РУКИ ══
  { id:'curl_bar', name:'Подъём штанги на бицепс стоя', group:'arms', type:'isolation', equipment:'barbell', difficulty:'beginner', jointStress:'low', fatigueCost:4, targetMuscle:'Бицепс (короткая головка)', order:2, substitutionGroup:'bicep_curl', canReplace:['curl_db','hammer_curl','cable_curl'], cannotReplace:['tricep_push','tricep_cable','dips_tricep'], technique:'Хват на ширине плеч. Не раскачивайтесь! Опускание 2-3 сек. Вверху — сжение 1 сек.', pauseSeconds:1, peakContraction:true, stretchPhase:true, comments:'Базовый бицепс. Хват шире = внешняя головка, уже = внутренняя.' },
  { id:'curl_db', name:'Подъём гантелей на бицепс стоя', group:'arms', type:'isolation', equipment:'dumbbell', difficulty:'beginner', jointStress:'low', fatigueCost:4, targetMuscle:'Бицепс', order:2, substitutionGroup:'bicep_curl', canReplace:['curl_bar','hammer_curl','cable_curl'], cannotReplace:['tricep_push','tricep_cable','dips_tricep'], technique:'Супинация (разворот кисти) наверху. Поочерёдно или одновременно.', pauseSeconds:1, peakContraction:true, stretchPhase:true, comments:'Супинация = пиковое сокращение. Это ключ к полному сокращению бицепса.' },
  { id:'hammer_curl', name:'Молотки (нейтральный хват)', group:'arms', type:'isolation', equipment:'dumbbell', difficulty:'beginner', jointStress:'low', fatigueCost:4, targetMuscle:'Брахиалис, плечелучевая', order:2, substitutionGroup:'bicep_curl', canReplace:['curl_db','curl_bar','rope_hammer'], cannotReplace:['tricep_push','tricep_cable'], technique:'Нейтральный хват (как молоток). Без супинации. Акцент на брахиалис.', pauseSeconds:1, peakContraction:true, stretchPhase:true, comments:'Брахиалис под бицепсом = визуально толще рука. Обязательное упражнение!' },
  { id:'preacher_curl', name:'Подъём на скамье Скотта', group:'arms', type:'isolation', equipment:'barbell', difficulty:'intermediate', jointStress:'med', fatigueCost:5, targetMuscle:'Бицепс (длинная головка, растяжение)', order:2, substitutionGroup:'bicep_curl_iso', canReplace:['incline_db_curl','spider_curl'], cannotReplace:['curl_bar','hammer_curl','tricep_push'], technique:'Подмышки на скамью. Полное растяжение внизу. Без читинга!', pauseSeconds:2, peakContraction:false, stretchPhase:true, comments:'Максимальное растяжение бицепса. Чистая изоляция без читинга.' },
  { id:'incline_db_curl', name:'Подъём гантелей на наклонной скамье', group:'arms', type:'isolation', equipment:'dumbbell', difficulty:'intermediate', jointStress:'low', fatigueCost:4, targetMuscle:'Бицепс (длинная головка)', order:2, substitutionGroup:'bicep_curl_iso', canReplace:['preacher_curl','spider_curl'], cannotReplace:['curl_bar','hammer_curl','tricep_push'], technique:'Скамья 30-45° наклон назад. Руки висят = растяжение. Супинация наверху.', pauseSeconds:2, peakContraction:true, stretchPhase:true, comments:'Растяжение длинной головки в стартовой позиции. Очень эффективно для массы.' },
  { id:'spider_curl', name:'Паучий подъём (лёжа на скамье лицом вниз)', group:'arms', type:'isolation', equipment:'dumbbell', difficulty:'intermediate', jointStress:'low', fatigueCost:5, targetMuscle:'Бицепс (пиковое сокращение)', order:2, substitutionGroup:'bicep_curl_iso', canReplace:['preacher_curl','cable_curl'], cannotReplace:['hammer_curl','tricep_push'], technique:'Лёжа лицом вниз на наклонной. Руки свободно висят. Чистое пиковое сокращение без паузы внизу.', pauseSeconds:0, peakContraction:true, stretchPhase:false, comments:'Максимальное пиковое сокращение. Без растяжения — фокус на сокращении.' },
  { id:'cable_curl', name:'Сгибания на бицепс в блоке', group:'arms', type:'isolation', equipment:'cable', difficulty:'beginner', jointStress:'low', fatigueCost:3, targetMuscle:'Бицепс', order:3, substitutionGroup:'bicep_curl', canReplace:['curl_bar','curl_db','hammer_curl'], cannotReplace:['tricep_push','dips_tricep'], technique:'Постоянное натяжение = преимущество блоков. Не отдыхайте внизу!', pauseSeconds:0, peakContraction:true, stretchPhase:false, comments:'Постоянное натяжение — отличие от гантелей/штанги. Отличный финал.' },
  { id:'tricep_push', name:'Французский жим лёжа (EZ-гриф)', group:'arms', type:'isolation', equipment:'barbell', difficulty:'intermediate', jointStress:'med', fatigueCost:5, targetMuscle:'Трицепс (длинная головка, растяжение)', order:2, substitutionGroup:'tricep_long', canReplace:['ohp_lying','db_skullcrusher'], cannotReplace:['curl_bar','hammer_curl','cable_curl'], technique:'Локти фиксированы. Опускание за голову = растяжение длинной головки. Не разводите локти!', pauseSeconds:1, peakContraction:false, stretchPhase:true, comments:'Растяжение длинной головки = ключ к росту трицепса. Не заменять жимом!' },
  { id:'db_skullcrusher', name:'Французский жим гантелями', group:'arms', type:'isolation', equipment:'dumbbell', difficulty:'intermediate', jointStress:'med', fatigueCost:5, targetMuscle:'Трицепс (длинная головка)', order:2, substitutionGroup:'tricep_long', canReplace:['tricep_push','ohp_lying'], cannotReplace:['curl_bar','hammer_curl'], technique:'Гантели за голову. Локти фиксированы. Растяжение в нижней точке.', pauseSeconds:1, peakContraction:false, stretchPhase:true, comments:'Больше амплитуды чем EZ-гриф. Каждая рука работает независимо.' },
  { id:'ohp_lying', name:'Жим лежа узким хватом', group:'arms', type:'compound', equipment:'barbell', difficulty:'intermediate', jointStress:'med', fatigueCost:6, targetMuscle:'Трицепс + грудь', order:1, substitutionGroup:'tricep_compound', canReplace:['dips_tricep','tricep_push'], cannotReplace:['curl_bar','cable_curl','hammer_curl'], technique:'Хват на ширине плеч. Локти вдоль тела. Гриф к низу груди.', pauseSeconds:1, peakContraction:true, stretchPhase:false, comments:'Компаунд для трицепса. Альтернатива французскому жиму, но больше грудь.' },
  { id:'tricep_cable', name:'Разгибания на трицепс в верхнем блоке', group:'arms', type:'isolation', equipment:'cable', difficulty:'beginner', jointStress:'low', fatigueCost:3, targetMuscle:'Трицепс (латеральная + медиальная)', order:3, substitutionGroup:'tricep_pushdown', canReplace:['rope_pushdown','overhead_tricep_ext'], cannotReplace:['curl_bar','hammer_curl','cable_curl'], technique:'Локти прижаты! Не двигайте плечо. Полное разгибание + задержка 1 сек. Разворачивайте кисти наружу на канатной рукоятке.', pauseSeconds:1, peakContraction:true, stretchPhase:false, comments:'Изоляция трицепса. Канат + разворот = больше латеральной головки.' },
  { id:'rope_pushdown', name:'Разгибания трицепса канатной рукояткой', group:'arms', type:'isolation', equipment:'cable', difficulty:'beginner', jointStress:'low', fatigueCost:3, targetMuscle:'Трицепс (латеральная головка)', order:3, substitutionGroup:'tricep_pushdown', canReplace:['tricep_cable','overhead_tricep_ext'], cannotReplace:['curl_bar','hammer_curl'], technique:'Развод каната наружу в конце = пиковое сокращение латеральной головки.', pauseSeconds:1, peakContraction:true, stretchPhase:false, comments:'Разворот каната = уникальное сокращение латеральной головки.' },
  { id:'overhead_tricep_ext', name:'Разгибания из-за головы в блоке', group:'arms', type:'isolation', equipment:'cable', difficulty:'beginner', jointStress:'low', fatigueCost:4, targetMuscle:'Трицепс (длинная головка)', order:3, substitutionGroup:'tricep_long', canReplace:['tricep_push','db_skullcrusher'], cannotReplace:['curl_bar','hammer_curl','cable_curl'], technique:'Руки за головой. Растяжение длинной головки. Полное разгибание наверху.', pauseSeconds:1, peakContraction:true, stretchPhase:true, comments:'Растяжение длинной головки в блоке. Отличная альтернатива французскому жиму.' },
  { id:'dips_tricep', name:'Отжимания на брусьях (трицепсовый стиль)', group:'arms', type:'compound', equipment:'bodyweight', difficulty:'intermediate', jointStress:'med', fatigueCost:6, targetMuscle:'Трицепс, передняя дельта', order:1, substitutionGroup:'tricep_compound', canReplace:['ohp_lying','bench_dips'], cannotReplace:['curl_bar','cable_curl','hammer_curl'], technique:'Корпус вертикально! Не наклоняйтесь вперёд (это грудной стиль). Локти назад.', pauseSeconds:0, peakContraction:false, stretchPhase:true, comments:'Вертикально = трицепс. Наклон вперёд = грудь. Не путайте!' },
  { id:'kickback', name:'Разгибание гантели в наклоне', group:'arms', type:'isolation', equipment:'dumbbell', difficulty:'beginner', jointStress:'low', fatigueCost:3, targetMuscle:'Трицепс (латеральная)', order:3, substitutionGroup:'tricep_pushdown', canReplace:['tricep_cable','rope_pushdown'], cannotReplace:['curl_bar','hammer_curl','preacher_curl'], technique:'Локоть фиксирован выше плеча. Полное разгибание. Удержание 1 сек.', pauseSeconds:1, peakContraction:true, stretchPhase:false, comments:'Пиковое сокращение трицепса. Не используйте тяжёлый вес — форма решает.' },
  { id:'wrist_curl', name:'Сгибания запястий со штангой', group:'arms', type:'isolation', equipment:'barbell', difficulty:'beginner', jointStress:'low', fatigueCost:2, targetMuscle:'Предплечья (сгибатели)', order:4, substitutionGroup:'forearm_iso', canReplace:['wrist_curl_db','wrist_roller'], cannotReplace:['curl_bar','hammer_curl','tricep_push'], technique:'Предплечья на бёдрах. Только запястья двигаются. Полная амплитуда.', pauseSeconds:1, peakContraction:true, stretchPhase:true, comments:'Для сильного хвата и массивных предплечий.' },
  { id:'wrist_curl_db', name:'Сгибания запястий с гантелями', group:'arms', type:'isolation', equipment:'dumbbell', difficulty:'beginner', jointStress:'low', fatigueCost:2, targetMuscle:'Предплечья', order:4, substitutionGroup:'forearm_iso', canReplace:['wrist_curl','wrist_roller'], cannotReplace:['curl_bar','hammer_curl'], technique:'По одной руке. Полная амплитуда запястий.', pauseSeconds:1, peakContraction:true, stretchPhase:true, comments:'Односторонняя работа предплечий.' },

  // ══ КОР ══
  { id:'plank', name:'Планка', group:'core', type:'isolation', equipment:'bodyweight', difficulty:'beginner', jointStress:'low', fatigueCost:3, targetMuscle:'Трансверсус, мультифидус', order:3, substitutionGroup:'core_stab', canReplace:['dead_bug','pallof_press'], cannotReplace:['cable_crunch','hanging_leg','ab_wheel'], technique:'Тело — прямая линия. Ягодицы напряжены. Втяните живот. Не провисайте!', pauseSeconds:0, peakContraction:false, stretchPhase:false, comments:'Стабилизация, не визуальный пресс. Фундамент всех упражнений.' },
  { id:'ab_wheel', name:'Ролик для пресса (ab wheel)', group:'core', type:'compound', equipment:'bodyweight', difficulty:'advanced', jointStress:'med', fatigueCost:6, targetMuscle:'Все мышцы кора', order:2, substitutionGroup:'core_anti_ext', canReplace:['plank','dead_bug'], cannotReplace:['cable_crunch','russian_twist'], technique:'Из стойки на коленях. Катите вперёд до растяжения. Не провисайте поясницу! Возврат мощным сокращением.', pauseSeconds:0, peakContraction:true, stretchPhase:true, comments:'Мощнейшее упражнение для кора. Антиэкстензия. Не круглите поясницу!' },
  { id:'hanging_leg', name:'Подъём ног в висе', group:'core', type:'compound', equipment:'bodyweight', difficulty:'intermediate', jointStress:'low', fatigueCost:5, targetMuscle:'Нижняя часть прямой мышцы', order:2, substitutionGroup:'core_flex', canReplace:['knee_raise','cable_crunch'], cannotReplace:['plank','dead_bug','pallof_press'], technique:'Без раскачки! Поднимайте ноги до параллели или выше. Медленное опускание (3 сек).', pauseSeconds:0, peakContraction:true, stretchPhase:false, comments:'Сгибание таза = ключ. Не просто поднимайте ноги — подкручивайте таз!' },
  { id:'knee_raise', name:'Подъём коленей в висе', group:'core', type:'compound', equipment:'bodyweight', difficulty:'beginner', jointStress:'low', fatigueCost:4, targetMuscle:'Нижний пресс', order:2, substitutionGroup:'core_flex', canReplace:['hanging_leg','cable_crunch'], cannotReplace:['plank','dead_bug'], technique:'Колени к груди. Подкрутите таз.', pauseSeconds:0, peakContraction:true, stretchPhase:false, comments:'Начальный вариант перед прямыми ногами.' },
  { id:'cable_crunch', name:'Скручивания в верхнем блоке', group:'core', type:'isolation', equipment:'cable', difficulty:'beginner', jointStress:'low', fatigueCost:3, targetMuscle:'Прямая мышца живота', order:3, substitutionGroup:'core_flex', canReplace:['hanging_leg','crunch_machine'], cannotReplace:['plank','dead_bug','pallof_press'], technique:'На коленях. Тяните канат вниз, скругляя спину. Сокращение пресса, не сгибание бедра!', pauseSeconds:1, peakContraction:true, stretchPhase:false, comments:'Нагружаемая флексия пресса. Не тяните руками — локти фиксированы!' },
  { id:'russian_twist', name:'Русский твист (с весом)', group:'core', type:'compound', equipment:'bodyweight', difficulty:'intermediate', jointStress:'med', fatigueCost:4, targetMuscle:'Косые мышцы', order:3, substitutionGroup:'core_rot', canReplace:['cable_woodchop','pallof_press'], cannotReplace:['plank','cable_crunch','hanging_leg'], technique:'С весом. Вращение плечами, не руками. Фиксированный таз.', pauseSeconds:0, peakContraction:true, stretchPhase:false, comments:'Косые мышцы. Не заменяет флексию пресса.' },
  { id:'pallof_press', name:'Паллоф-пресс (антиротация)', group:'core', type:'isolation', equipment:'cable', difficulty:'intermediate', jointStress:'low', fatigueCost:4, targetMuscle:'Косые (антиротация), кор', order:3, substitutionGroup:'core_stab', canReplace:['plank','dead_bug','cable_woodchop'], cannotReplace:['cable_crunch','hanging_leg','russian_twist'], technique:'Трос сбоку. Выжимаете прямо перед собой — сопротивление ротации! 3-5 сек удержание.', pauseSeconds:3, peakContraction:true, stretchPhase:false, comments:'Незаменимое упражнение для антиротации. Предотвращает травмы спины.' },
  { id:'dead_bug', name:'Мёртвый жук', group:'core', type:'isolation', equipment:'bodyweight', difficulty:'beginner', jointStress:'low', fatigueCost:3, targetMuscle:'Кора (антиэкстензия)', order:3, substitutionGroup:'core_stab', canReplace:['plank','pallof_press'], cannotReplace:['cable_crunch','hanging_leg','russian_twist'], technique:'На спине. Рука + противоположная нога. Поясница прижата! Не прогибайтесь.', pauseSeconds:1, peakContraction:false, stretchPhase:false, comments:'Фундаментальная антиэкстензия. Если поясница отрывается — делайте проще.' },
  { id:'hyperextension', name:'Гиперэкстензия (45°)', group:'core', type:'isolation', equipment:'machine', difficulty:'beginner', jointStress:'low', fatigueCost:3, targetMuscle:'Разгибатели спины', order:3, substitutionGroup:'erector_iso', canReplace:['good_morning','back_extension'], cannotReplace:['plank','cable_crunch','hanging_leg'], technique:'Валик на верхней части бёдер. Опускание с круглой спиной. Подъём до прямой линии — не гиперэкстензия!', pauseSeconds:1, peakContraction:false, stretchPhase:true, comments:'Разгибатели спины. Не выгибайтесь назад — это повреждение!' },
  // ══ АРМРЕСТЛИНГ ══
  { id:'wrist_curl', name:'Сгибание кисти со штангой', group:'arms', type:'isolation', equipment:'barbell', difficulty:'beginner', jointStress:'low', fatigueCost:4, targetMuscle:'Сгибатели предплечья', order:3, substitutionGroup:'wrist_curl', canReplace:['wrist_curl_db','wrist_curl_reverse'], cannotReplace:['curl_bar','hammer_curl'], technique:'Предплечья на бёдрах, гриф в хвате сверху. Сгибание только кистью. Не отрывайте предплечья!', pauseSeconds:1, peakContraction:true, stretchPhase:false, comments:'Базовое упражнение для хвата и пронации в армрестлинге.' },
  { id:'wrist_curl_db', name:'Сгибание кисти с гантелей', group:'arms', type:'isolation', equipment:'dumbbell', difficulty:'beginner', jointStress:'low', fatigueCost:3, targetMuscle:'Сгибатели предплечья', order:3, substitutionGroup:'wrist_curl', canReplace:['wrist_curl'], cannotReplace:['curl_bar','hammer_curl'], technique:'Одной рукой. Предплечье на бедре. Полная амплитуда кистью.', pauseSeconds:1, peakContraction:true, stretchPhase:false, comments:'Односторонняя работа, лучше для баланса.' },
  { id:'wrist_curl_reverse', name:'Разгибание кисти (обратный хват)', group:'arms', type:'isolation', equipment:'barbell', difficulty:'beginner', jointStress:'low', fatigueCost:3, targetMuscle:'Разгибатели предплечья', order:4, substitutionGroup:'wrist_ext', canReplace:['wrist_curl_reverse_db'], cannotReplace:['curl_bar','wrist_curl'], technique:'Хват снизу. Разгибание кисти вверх. Предплечья прижаты.', pauseSeconds:1, peakContraction:true, stretchPhase:false, comments:'Укрепляет разгибатели — важно для пронации и контроля в армрестлинге.' },
  { id:'pronation_dumbbell', name:'Пронация с гантелью (рычаг)', group:'arms', type:'isolation', equipment:'dumbbell', difficulty:'intermediate', jointStress:'med', fatigueCost:5, targetMuscle:'Пронаторы предплечья', order:2, substitutionGroup:'pronation', canReplace:['pronation_cable'], cannotReplace:['wrist_curl','curl_bar'], technique:'Гантель за один конец. Локоть прижат. Вращение предплечья внутрь (пронация). Контроль!', pauseSeconds:1, peakContraction:true, stretchPhase:false, comments:'Специфичное упражнение для армрестлинга. Пронация — ключевое движение в крюке.' },
  { id:'sledgehammer_lever', name:'Леверинг молота/гантели', group:'arms', type:'isolation', equipment:'dumbbell', difficulty:'advanced', jointStress:'med', fatigueCost:6, targetMuscle:'Сгибатели + пронаторы предплечья', order:2, substitutionGroup:'lever', canReplace:['pronation_dumbbell'], cannotReplace:['wrist_curl','curl_bar'], technique:'Держите гантель за один конец. Поднимайте кистью вверх-вперёд. Удержание 2 сек.', pauseSeconds:2, peakContraction:true, stretchPhase:false, comments:'Продвинутое упражнение для рычага в армрестлинге. Развивает силу хвата и запястья.' },
  { id:'hub_pinch', name:'Хаб-пинч (pinch grip)', group:'arms', type:'isolation', equipment:'plate', difficulty:'intermediate', jointStress:'low', fatigueCost:5, targetMuscle:'Щипковый хват', order:3, substitutionGroup:'grip', canReplace:['plate_pinch','farmer_walk'], cannotReplace:['wrist_curl','curl_bar'], technique:'Две блины вместе. Зажимайте пальцами. Удержание 15-30 сек.', pauseSeconds:0, peakContraction:true, stretchPhase:false, comments:'Специфичный для армрестлинга хват — укрепляет пальцы и ладонь.' },
  { id:'farmer_walk', name:'Фермерская прогулка', group:'arms', type:'compound', equipment:'dumbbell', difficulty:'intermediate', jointStress:'med', fatigueCost:7, targetMuscle:'Хват, трапеции, кор', order:1, substitutionGroup:'grip', canReplace:['hub_pinch','plate_pinch'], cannotReplace:['wrist_curl'], technique:'Тяжёлые гантели в руках. Ходьба 30-60 сек. Прямая осанка. Не отпускайте!', pauseSeconds:0, peakContraction:false, stretchPhase:false, comments:'Отличное упражнение для хвата, кор и ловушки. Переносится на армрестлинг.' },
  // ══ ТЯЖЁЛАЯ АТЛЕТИКА ══
  { id:'front_squat_clean', name:'Фронтальный присед (рывковый)', group:'legs', type:'compound', equipment:'barbell', difficulty:'advanced', jointStress:'med', fatigueCost:8, targetMuscle:'Квадрицепсы, кор', order:1, substitutionGroup:'squat_var', canReplace:['front_squat','squat'], cannotReplace:['leg_ext','leg_curl'], technique:'Гриф на передних дельтах, локти высоко. Полный присед. Грудь вперёд. Вес на пятках.', pauseSeconds:1, peakContraction:false, stretchPhase:true, comments:'Ключевое упражнение для толчка в тяжёлой атлетике.' },
  { id:'overhead_squat', name:'Присед со штангой над головой', group:'legs', type:'compound', equipment:'barbell', difficulty:'advanced', jointStress:'high', fatigueCost:8, targetMuscle:'Квадрицепсы, дельты, кор', order:2, substitutionGroup:'squat_var', canReplace:['squat','front_squat'], cannotReplace:['leg_ext','calf_raise'], technique:'Штанга над головой на вытянутых руках. Полный присед. Активный кор, грудь вперёд!', pauseSeconds:1, peakContraction:false, stretchPhase:true, comments:'Уникальная подвижность и стабильность. Ключевое для рывка.' },
  { id:'push_press_jerk', name:'Жимовой швунг/толчок', group:'shoulders', type:'compound', equipment:'barbell', difficulty:'advanced', jointStress:'high', fatigueCost:8, targetMuscle:'Дельты, трицепс, кор, ноги', order:1, substitutionGroup:'vert_push', canReplace:['ohp','push_press'], cannotReplace:['lateral_raise','rear_delt_fly'], technique:'Движение начинается ногами! Подсед + жим. Полный выпрям локтей над головой.', pauseSeconds:1, peakContraction:true, stretchPhase:false, comments:'Толчок в тяжёлой атлетике. Ноги = основной драйвер, руки = финаш.' },
  { id:'clean_pull', name:'Тяга рывковая/толчковая (до колен)', group:'back', type:'compound', equipment:'barbell', difficulty:'advanced', jointStress:'med', fatigueCost:7, targetMuscle:'Разгибатели, трапеции, задняя цепь', order:1, substitutionGroup:'hip_hinge', canReplace:['deadlift','rdl'], cannotReplace:['pulldown','seated_row'], technique:'Начало тяги с пола. Движение — как первая часть рывка/толчка. Подрыв + подъём на носки.', pauseSeconds:1, peakContraction:false, stretchPhase:false, comments:'Специфическая тяга для тяжёлой атлетики. Учит правильному первому тяговому движению.' },
  { id:'muscle_snatch', name:'Рывок мышцами (без подседа)', group:'back', type:'compound', equipment:'barbell', difficulty:'advanced', jointStress:'high', fatigueCost:9, targetMuscle:'Широчайшие, дельты, задняя цепь', order:1, substitutionGroup:'vert_pull', canReplace:['pullup','pulldown'], cannotReplace:['seated_row','face_pull'], technique:'Подъём штанги над головой без подседа. Мощный подрыв + тяга. Без подседа — чисто мышечная сила.', pauseSeconds:0, peakContraction:true, stretchPhase:false, comments:'Обучение рывку без технической сложности подседа. Укрепляетpull.' },
];

export const SUBSTITUTION_MAP: ExerciseSubstitution[] = [
  { exerciseId:'squat', substitutes:[{id:'front_squat',reason:'Меньше поясницы, больше квадрицепс',priority:1},{id:'hack_squat',reason:'Машинная альтернатива',priority:2},{id:'squat_ssb',reason:'При болях в плечах',priority:3},{id:'leg_press',reason:'Машинная, безопаснее',priority:4}], forbidden:[{id:'leg_ext',reason:'Разгибания ног — изоляция квадрицепса, не заменяет компаунд-присед'},{id:'calf_raise',reason:'Совершенно другая мышечная группа'},{id:'leg_curl',reason:'Бицепс бедра, не квадрицепс'}] },
  { exerciseId:'bench_bar', substitutes:[{id:'bench_db',reason:'Больше амплитуда',priority:1},{id:'incline_bar',reason:'Смещение акцента на верх',priority:2}], forbidden:[{id:'cable_fly',reason:'Изоляция, не заменяет компаунд'},{id:'pec_deck',reason:'Изоляция'},{id:'fly_db',reason:'Изоляция'}] },
  { exerciseId:'deadlift', substitutes:[{id:'sumo_dl',reason:'Меньше поясница',priority:1},{id:'rdl',reason:'Задняя цепь без стартовой тяги',priority:2},{id:'good_morning',reason:'Альтернатива задней цепи',priority:3}], forbidden:[{id:'pulldown',reason:'Вертикальная тяга не заменяет становую'},{id:'seated_row',reason:'Горизонтальная тяга — другая плоскость'}] },
  { exerciseId:'pullup', substitutes:[{id:'pulldown',reason:'Если не можете подтягиваться',priority:1},{id:'chinup',reason:'Больше бицепса',priority:2},{id:'pullup_neutral',reason:'Безопаснее для плеч',priority:3}], forbidden:[{id:'face_pull',reason:'Задняя дельта/ромбовидные — не широчайшие'},{id:'straight_pull',reason:'Изоляция — не компаунд'}] },
  { exerciseId:'ohp', substitutes:[{id:'db_press',reason:'Больше амплитуда',priority:1},{id:'ohp_seated',reason:'Без ног, чище изоляция',priority:2},{id:'push_press',reason:'Больше вес за счёт ног',priority:3}], forbidden:[{id:'lateral_raise',reason:'Изоляция средней дельты'},{id:'rear_delt_fly',reason:'Задняя дельта — другая мышца'}] },
  { exerciseId:'rdl', substitutes:[{id:'rdl_db',reason:'Гантели при проблемах с хватом',priority:1},{id:'good_morning',reason:'Задняя цепь со штангой на спине',priority:2}], forbidden:[{id:'leg_curl',reason:'Изоляция, не заменяет компаунд задней цепи'},{id:'leg_ext',reason:'Квадрицепс'}] },
  { exerciseId:'row_bar', substitutes:[{id:'row_db',reason:'Односторонняя работа',priority:1},{id:'row_tbar',reason:'Центр спины',priority:2},{id:'seated_row',reason:'Машинная альтернатива',priority:3}], forbidden:[{id:'pulldown',reason:'Вертикальная тяга — другая плоскость'},{id:'face_pull',reason:'Задняя дельта'}] },
];

export function getSubstitutes(exerciseId: string): ExerciseSubstitution | undefined {
  return SUBSTITUTION_MAP.find(s => s.exerciseId === exerciseId);
}

export function canReplace(exA: string, exB: string): boolean {
  const a = EXERCISE_CATALOG.find(e => e.id === exA);
  const b = EXERCISE_CATALOG.find(e => e.id === exB);
  if (!a || !b) return false;
  if (a.cannotReplace?.includes(exB)) return false;
  if (b.cannotReplace?.includes(exA)) return false;
  if (a.substitutionGroup && b.substitutionGroup && a.substitutionGroup === b.substitutionGroup) return true;
  if (a.canReplace?.includes(exB)) return true;
  return false;
}

export function getExerciseById(id: string): Exercise | undefined {
  return EXERCISE_CATALOG.find(e => e.id === id);
}

export function getExercisesByGroup(group: string): Exercise[] {
  return EXERCISE_CATALOG.filter(e => e.group === group);
}

export function getExercisesBySubstitutionGroup(sg: string): Exercise[] {
  return EXERCISE_CATALOG.filter(e => e.substitutionGroup === sg);
}